// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_statistics`, `clean_contact`, `clean_optional`, `clean_required`, `keyword_similarity`, `keywords`, `load_reports`, `matches_for`, `next_id`, `normalize`, `reports_path`, `same`, `save_reports`, `score_pair`, `validate_date`, `validate_new`, `validate_update`

/// Removes data left by the retired audit-ledger experiment from older builds.
Future<bool> cleanupLegacyData({required String storageDir}) => RustLib
    .instance
    .api
    .crateApiFinditCleanupLegacyData(storageDir: storageDir);

Future<ItemReport> addReport({
  required String storageDir,
  required NewReportInput input,
}) => RustLib.instance.api.crateApiFinditAddReport(
  storageDir: storageDir,
  input: input,
);

Future<ItemReport> updateReport({
  required String storageDir,
  required String id,
  required UpdateReportInput input,
}) => RustLib.instance.api.crateApiFinditUpdateReport(
  storageDir: storageDir,
  id: id,
  input: input,
);

Future<void> deleteReport({required String storageDir, required String id}) =>
    RustLib.instance.api.crateApiFinditDeleteReport(
      storageDir: storageDir,
      id: id,
    );

Future<ItemReport> getReport({
  required String storageDir,
  required String id,
}) => RustLib.instance.api.crateApiFinditGetReport(
  storageDir: storageDir,
  id: id,
);

Future<List<ItemReport>> getReports({
  required String storageDir,
  String? search,
  ItemStatus? status,
}) => RustLib.instance.api.crateApiFinditGetReports(
  storageDir: storageDir,
  search: search,
  status: status,
);

Future<Statistics> getStatistics({required String storageDir}) =>
    RustLib.instance.api.crateApiFinditGetStatistics(storageDir: storageDir);

Future<List<MatchResult>> findMatches({
  required String storageDir,
  String? reportId,
}) => RustLib.instance.api.crateApiFinditFindMatches(
  storageDir: storageDir,
  reportId: reportId,
);

Future<void> markAsReturned({
  required String storageDir,
  required String lostId,
  required String foundId,
}) => RustLib.instance.api.crateApiFinditMarkAsReturned(
  storageDir: storageDir,
  lostId: lostId,
  foundId: foundId,
);

Future<ItemReport> markReportAsReturned({
  required String storageDir,
  required String id,
}) => RustLib.instance.api.crateApiFinditMarkReportAsReturned(
  storageDir: storageDir,
  id: id,
);

Future<bool> isDevelopment() =>
    RustLib.instance.api.crateApiFinditIsDevelopment();

Future<List<ItemReport>> seedSampleData({required String storageDir}) =>
    RustLib.instance.api.crateApiFinditSeedSampleData(storageDir: storageDir);
