// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_report_type`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class ItemReport {
  final String id;
  final String itemName;
  final String category;
  final String color;
  final String location;
  final String date;
  final String description;
  final String? contactInformation;
  final ReportType reportType;
  final ItemStatus status;

  /// RFC 3339 text keeps the bridge type beginner-friendly and sorts correctly.
  final String createdAt;

  const ItemReport({
    required this.id,
    required this.itemName,
    required this.category,
    required this.color,
    required this.location,
    required this.date,
    required this.description,
    this.contactInformation,
    required this.reportType,
    required this.status,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      itemName.hashCode ^
      category.hashCode ^
      color.hashCode ^
      location.hashCode ^
      date.hashCode ^
      description.hashCode ^
      contactInformation.hashCode ^
      reportType.hashCode ^
      status.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemReport &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          itemName == other.itemName &&
          category == other.category &&
          color == other.color &&
          location == other.location &&
          date == other.date &&
          description == other.description &&
          contactInformation == other.contactInformation &&
          reportType == other.reportType &&
          status == other.status &&
          createdAt == other.createdAt;
}

enum ItemStatus { lost, found, returned }

class MatchReason {
  final String label;
  final int points;
  final int maxPoints;
  final bool matched;

  const MatchReason({
    required this.label,
    required this.points,
    required this.maxPoints,
    required this.matched,
  });

  @override
  int get hashCode =>
      label.hashCode ^ points.hashCode ^ maxPoints.hashCode ^ matched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchReason &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          points == other.points &&
          maxPoints == other.maxPoints &&
          matched == other.matched;
}

class MatchResult {
  final ItemReport lostReport;
  final ItemReport foundReport;
  final int score;
  final String quality;
  final List<MatchReason> reasons;

  const MatchResult({
    required this.lostReport,
    required this.foundReport,
    required this.score,
    required this.quality,
    required this.reasons,
  });

  @override
  int get hashCode =>
      lostReport.hashCode ^
      foundReport.hashCode ^
      score.hashCode ^
      quality.hashCode ^
      reasons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchResult &&
          runtimeType == other.runtimeType &&
          lostReport == other.lostReport &&
          foundReport == other.foundReport &&
          score == other.score &&
          quality == other.quality &&
          reasons == other.reasons;
}

class NewReportInput {
  final String itemName;
  final String category;
  final String color;
  final String location;
  final String date;
  final String description;
  final String? contactInformation;
  final ReportType reportType;

  const NewReportInput({
    required this.itemName,
    required this.category,
    required this.color,
    required this.location,
    required this.date,
    required this.description,
    this.contactInformation,
    required this.reportType,
  });

  @override
  int get hashCode =>
      itemName.hashCode ^
      category.hashCode ^
      color.hashCode ^
      location.hashCode ^
      date.hashCode ^
      description.hashCode ^
      contactInformation.hashCode ^
      reportType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewReportInput &&
          runtimeType == other.runtimeType &&
          itemName == other.itemName &&
          category == other.category &&
          color == other.color &&
          location == other.location &&
          date == other.date &&
          description == other.description &&
          contactInformation == other.contactInformation &&
          reportType == other.reportType;
}

enum ReportType { lost, found }

class Statistics {
  final int lost;
  final int found;
  final int returned;
  final int total;

  const Statistics({
    required this.lost,
    required this.found,
    required this.returned,
    required this.total,
  });

  static Future<Statistics> default_() =>
      RustLib.instance.api.crateApiModelsStatisticsDefault();

  @override
  int get hashCode =>
      lost.hashCode ^ found.hashCode ^ returned.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Statistics &&
          runtimeType == other.runtimeType &&
          lost == other.lost &&
          found == other.found &&
          returned == other.returned &&
          total == other.total;
}

class UpdateReportInput {
  final String itemName;
  final String category;
  final String color;
  final String location;
  final String date;
  final String description;
  final String? contactInformation;

  const UpdateReportInput({
    required this.itemName,
    required this.category,
    required this.color,
    required this.location,
    required this.date,
    required this.description,
    this.contactInformation,
  });

  @override
  int get hashCode =>
      itemName.hashCode ^
      category.hashCode ^
      color.hashCode ^
      location.hashCode ^
      date.hashCode ^
      description.hashCode ^
      contactInformation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateReportInput &&
          runtimeType == other.runtimeType &&
          itemName == other.itemName &&
          category == other.category &&
          color == other.color &&
          location == other.location &&
          date == other.date &&
          description == other.description &&
          contactInformation == other.contactInformation;
}
