// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/findit.dart';
import 'api/models.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiFinditInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 153517317;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'findit_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ItemReport> crateApiFinditAddReport({
    required String storageDir,
    required NewReportInput input,
  });

  Future<bool> crateApiFinditCleanupLegacyData({required String storageDir});

  Future<void> crateApiFinditDeleteReport({
    required String storageDir,
    required String id,
  });

  Future<List<MatchResult>> crateApiFinditFindMatches({
    required String storageDir,
    String? reportId,
  });

  Future<ItemReport> crateApiFinditGetReport({
    required String storageDir,
    required String id,
  });

  Future<List<ItemReport>> crateApiFinditGetReports({
    required String storageDir,
    String? search,
    ItemStatus? status,
  });

  Future<Statistics> crateApiFinditGetStatistics({required String storageDir});

  Future<void> crateApiFinditInitApp();

  Future<bool> crateApiFinditIsDevelopment();

  Future<void> crateApiFinditMarkAsReturned({
    required String storageDir,
    required String lostId,
    required String foundId,
  });

  Future<ItemReport> crateApiFinditMarkReportAsReturned({
    required String storageDir,
    required String id,
  });

  Future<List<ItemReport>> crateApiFinditSeedSampleData({
    required String storageDir,
  });

  Future<Statistics> crateApiModelsStatisticsDefault();

  Future<ItemReport> crateApiFinditUpdateReport({
    required String storageDir,
    required String id,
    required UpdateReportInput input,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ItemReport> crateApiFinditAddReport({
    required String storageDir,
    required NewReportInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_box_autoadd_new_report_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_item_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditAddReportConstMeta,
        argValues: [storageDir, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditAddReportConstMeta => const TaskConstMeta(
    debugName: "add_report",
    argNames: ["storageDir", "input"],
  );

  @override
  Future<bool> crateApiFinditCleanupLegacyData({required String storageDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditCleanupLegacyDataConstMeta,
        argValues: [storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditCleanupLegacyDataConstMeta =>
      const TaskConstMeta(
        debugName: "cleanup_legacy_data",
        argNames: ["storageDir"],
      );

  @override
  Future<void> crateApiFinditDeleteReport({
    required String storageDir,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditDeleteReportConstMeta,
        argValues: [storageDir, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditDeleteReportConstMeta => const TaskConstMeta(
    debugName: "delete_report",
    argNames: ["storageDir", "id"],
  );

  @override
  Future<List<MatchResult>> crateApiFinditFindMatches({
    required String storageDir,
    String? reportId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_opt_String(reportId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_match_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditFindMatchesConstMeta,
        argValues: [storageDir, reportId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditFindMatchesConstMeta => const TaskConstMeta(
    debugName: "find_matches",
    argNames: ["storageDir", "reportId"],
  );

  @override
  Future<ItemReport> crateApiFinditGetReport({
    required String storageDir,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_item_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditGetReportConstMeta,
        argValues: [storageDir, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditGetReportConstMeta => const TaskConstMeta(
    debugName: "get_report",
    argNames: ["storageDir", "id"],
  );

  @override
  Future<List<ItemReport>> crateApiFinditGetReports({
    required String storageDir,
    String? search,
    ItemStatus? status,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_opt_String(search, serializer);
          sse_encode_opt_box_autoadd_item_status(status, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_item_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditGetReportsConstMeta,
        argValues: [storageDir, search, status],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditGetReportsConstMeta => const TaskConstMeta(
    debugName: "get_reports",
    argNames: ["storageDir", "search", "status"],
  );

  @override
  Future<Statistics> crateApiFinditGetStatistics({required String storageDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_statistics,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditGetStatisticsConstMeta,
        argValues: [storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditGetStatisticsConstMeta =>
      const TaskConstMeta(
        debugName: "get_statistics",
        argNames: ["storageDir"],
      );

  @override
  Future<void> crateApiFinditInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFinditInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiFinditIsDevelopment() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFinditIsDevelopmentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditIsDevelopmentConstMeta =>
      const TaskConstMeta(debugName: "is_development", argNames: []);

  @override
  Future<void> crateApiFinditMarkAsReturned({
    required String storageDir,
    required String lostId,
    required String foundId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(lostId, serializer);
          sse_encode_String(foundId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditMarkAsReturnedConstMeta,
        argValues: [storageDir, lostId, foundId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditMarkAsReturnedConstMeta =>
      const TaskConstMeta(
        debugName: "mark_as_returned",
        argNames: ["storageDir", "lostId", "foundId"],
      );

  @override
  Future<ItemReport> crateApiFinditMarkReportAsReturned({
    required String storageDir,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_item_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditMarkReportAsReturnedConstMeta,
        argValues: [storageDir, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditMarkReportAsReturnedConstMeta =>
      const TaskConstMeta(
        debugName: "mark_report_as_returned",
        argNames: ["storageDir", "id"],
      );

  @override
  Future<List<ItemReport>> crateApiFinditSeedSampleData({
    required String storageDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_item_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditSeedSampleDataConstMeta,
        argValues: [storageDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditSeedSampleDataConstMeta =>
      const TaskConstMeta(
        debugName: "seed_sample_data",
        argNames: ["storageDir"],
      );

  @override
  Future<Statistics> crateApiModelsStatisticsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_statistics,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsStatisticsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsStatisticsDefaultConstMeta =>
      const TaskConstMeta(debugName: "statistics_default", argNames: []);

  @override
  Future<ItemReport> crateApiFinditUpdateReport({
    required String storageDir,
    required String id,
    required UpdateReportInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDir, serializer);
          sse_encode_String(id, serializer);
          sse_encode_box_autoadd_update_report_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_item_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFinditUpdateReportConstMeta,
        argValues: [storageDir, id, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinditUpdateReportConstMeta => const TaskConstMeta(
    debugName: "update_report",
    argNames: ["storageDir", "id", "input"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ItemStatus dco_decode_box_autoadd_item_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_item_status(raw);
  }

  @protected
  NewReportInput dco_decode_box_autoadd_new_report_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_new_report_input(raw);
  }

  @protected
  UpdateReportInput dco_decode_box_autoadd_update_report_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_update_report_input(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ItemReport dco_decode_item_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ItemReport(
      id: dco_decode_String(arr[0]),
      itemName: dco_decode_String(arr[1]),
      category: dco_decode_String(arr[2]),
      color: dco_decode_String(arr[3]),
      location: dco_decode_String(arr[4]),
      date: dco_decode_String(arr[5]),
      description: dco_decode_String(arr[6]),
      contactInformation: dco_decode_opt_String(arr[7]),
      reportType: dco_decode_report_type(arr[8]),
      status: dco_decode_item_status(arr[9]),
      createdAt: dco_decode_String(arr[10]),
    );
  }

  @protected
  ItemStatus dco_decode_item_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ItemStatus.values[raw as int];
  }

  @protected
  List<ItemReport> dco_decode_list_item_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_item_report).toList();
  }

  @protected
  List<MatchReason> dco_decode_list_match_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_match_reason).toList();
  }

  @protected
  List<MatchResult> dco_decode_list_match_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_match_result).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MatchReason dco_decode_match_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MatchReason(
      label: dco_decode_String(arr[0]),
      points: dco_decode_u_8(arr[1]),
      maxPoints: dco_decode_u_8(arr[2]),
      matched: dco_decode_bool(arr[3]),
    );
  }

  @protected
  MatchResult dco_decode_match_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MatchResult(
      lostReport: dco_decode_item_report(arr[0]),
      foundReport: dco_decode_item_report(arr[1]),
      score: dco_decode_u_8(arr[2]),
      quality: dco_decode_String(arr[3]),
      reasons: dco_decode_list_match_reason(arr[4]),
    );
  }

  @protected
  NewReportInput dco_decode_new_report_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return NewReportInput(
      itemName: dco_decode_String(arr[0]),
      category: dco_decode_String(arr[1]),
      color: dco_decode_String(arr[2]),
      location: dco_decode_String(arr[3]),
      date: dco_decode_String(arr[4]),
      description: dco_decode_String(arr[5]),
      contactInformation: dco_decode_opt_String(arr[6]),
      reportType: dco_decode_report_type(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ItemStatus? dco_decode_opt_box_autoadd_item_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_item_status(raw);
  }

  @protected
  ReportType dco_decode_report_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReportType.values[raw as int];
  }

  @protected
  Statistics dco_decode_statistics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Statistics(
      lost: dco_decode_u_32(arr[0]),
      found: dco_decode_u_32(arr[1]),
      returned: dco_decode_u_32(arr[2]),
      total: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateReportInput dco_decode_update_report_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return UpdateReportInput(
      itemName: dco_decode_String(arr[0]),
      category: dco_decode_String(arr[1]),
      color: dco_decode_String(arr[2]),
      location: dco_decode_String(arr[3]),
      date: dco_decode_String(arr[4]),
      description: dco_decode_String(arr[5]),
      contactInformation: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ItemStatus sse_decode_box_autoadd_item_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_item_status(deserializer));
  }

  @protected
  NewReportInput sse_decode_box_autoadd_new_report_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_new_report_input(deserializer));
  }

  @protected
  UpdateReportInput sse_decode_box_autoadd_update_report_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_update_report_input(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ItemReport sse_decode_item_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_itemName = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_contactInformation = sse_decode_opt_String(deserializer);
    var var_reportType = sse_decode_report_type(deserializer);
    var var_status = sse_decode_item_status(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return ItemReport(
      id: var_id,
      itemName: var_itemName,
      category: var_category,
      color: var_color,
      location: var_location,
      date: var_date,
      description: var_description,
      contactInformation: var_contactInformation,
      reportType: var_reportType,
      status: var_status,
      createdAt: var_createdAt,
    );
  }

  @protected
  ItemStatus sse_decode_item_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ItemStatus.values[inner];
  }

  @protected
  List<ItemReport> sse_decode_list_item_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ItemReport>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_item_report(deserializer));
    }
    return ans_;
  }

  @protected
  List<MatchReason> sse_decode_list_match_reason(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MatchReason>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_match_reason(deserializer));
    }
    return ans_;
  }

  @protected
  List<MatchResult> sse_decode_list_match_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MatchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_match_result(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MatchReason sse_decode_match_reason(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_points = sse_decode_u_8(deserializer);
    var var_maxPoints = sse_decode_u_8(deserializer);
    var var_matched = sse_decode_bool(deserializer);
    return MatchReason(
      label: var_label,
      points: var_points,
      maxPoints: var_maxPoints,
      matched: var_matched,
    );
  }

  @protected
  MatchResult sse_decode_match_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lostReport = sse_decode_item_report(deserializer);
    var var_foundReport = sse_decode_item_report(deserializer);
    var var_score = sse_decode_u_8(deserializer);
    var var_quality = sse_decode_String(deserializer);
    var var_reasons = sse_decode_list_match_reason(deserializer);
    return MatchResult(
      lostReport: var_lostReport,
      foundReport: var_foundReport,
      score: var_score,
      quality: var_quality,
      reasons: var_reasons,
    );
  }

  @protected
  NewReportInput sse_decode_new_report_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_itemName = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_contactInformation = sse_decode_opt_String(deserializer);
    var var_reportType = sse_decode_report_type(deserializer);
    return NewReportInput(
      itemName: var_itemName,
      category: var_category,
      color: var_color,
      location: var_location,
      date: var_date,
      description: var_description,
      contactInformation: var_contactInformation,
      reportType: var_reportType,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ItemStatus? sse_decode_opt_box_autoadd_item_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_item_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReportType sse_decode_report_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReportType.values[inner];
  }

  @protected
  Statistics sse_decode_statistics(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lost = sse_decode_u_32(deserializer);
    var var_found = sse_decode_u_32(deserializer);
    var var_returned = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    return Statistics(
      lost: var_lost,
      found: var_found,
      returned: var_returned,
      total: var_total,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateReportInput sse_decode_update_report_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_itemName = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_contactInformation = sse_decode_opt_String(deserializer);
    return UpdateReportInput(
      itemName: var_itemName,
      category: var_category,
      color: var_color,
      location: var_location,
      date: var_date,
      description: var_description,
      contactInformation: var_contactInformation,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_item_status(
    ItemStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_item_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_new_report_input(
    NewReportInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_new_report_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_update_report_input(
    UpdateReportInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_update_report_input(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_item_report(ItemReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.itemName, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_opt_String(self.contactInformation, serializer);
    sse_encode_report_type(self.reportType, serializer);
    sse_encode_item_status(self.status, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_item_status(ItemStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_item_report(
    List<ItemReport> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_item_report(item, serializer);
    }
  }

  @protected
  void sse_encode_list_match_reason(
    List<MatchReason> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_match_reason(item, serializer);
    }
  }

  @protected
  void sse_encode_list_match_result(
    List<MatchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_match_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_match_reason(MatchReason self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_u_8(self.points, serializer);
    sse_encode_u_8(self.maxPoints, serializer);
    sse_encode_bool(self.matched, serializer);
  }

  @protected
  void sse_encode_match_result(MatchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_item_report(self.lostReport, serializer);
    sse_encode_item_report(self.foundReport, serializer);
    sse_encode_u_8(self.score, serializer);
    sse_encode_String(self.quality, serializer);
    sse_encode_list_match_reason(self.reasons, serializer);
  }

  @protected
  void sse_encode_new_report_input(
    NewReportInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.itemName, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_opt_String(self.contactInformation, serializer);
    sse_encode_report_type(self.reportType, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_item_status(
    ItemStatus? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_item_status(self, serializer);
    }
  }

  @protected
  void sse_encode_report_type(ReportType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_statistics(Statistics self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.lost, serializer);
    sse_encode_u_32(self.found, serializer);
    sse_encode_u_32(self.returned, serializer);
    sse_encode_u_32(self.total, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_report_input(
    UpdateReportInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.itemName, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_opt_String(self.contactInformation, serializer);
  }
}
