// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/findit.dart';
import 'api/models.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ItemStatus dco_decode_box_autoadd_item_status(dynamic raw);

  @protected
  NewReportInput dco_decode_box_autoadd_new_report_input(dynamic raw);

  @protected
  UpdateReportInput dco_decode_box_autoadd_update_report_input(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ItemReport dco_decode_item_report(dynamic raw);

  @protected
  ItemStatus dco_decode_item_status(dynamic raw);

  @protected
  List<ItemReport> dco_decode_list_item_report(dynamic raw);

  @protected
  List<MatchReason> dco_decode_list_match_reason(dynamic raw);

  @protected
  List<MatchResult> dco_decode_list_match_result(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MatchReason dco_decode_match_reason(dynamic raw);

  @protected
  MatchResult dco_decode_match_result(dynamic raw);

  @protected
  NewReportInput dco_decode_new_report_input(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ItemStatus? dco_decode_opt_box_autoadd_item_status(dynamic raw);

  @protected
  ReportType dco_decode_report_type(dynamic raw);

  @protected
  Statistics dco_decode_statistics(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateReportInput dco_decode_update_report_input(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ItemStatus sse_decode_box_autoadd_item_status(SseDeserializer deserializer);

  @protected
  NewReportInput sse_decode_box_autoadd_new_report_input(
    SseDeserializer deserializer,
  );

  @protected
  UpdateReportInput sse_decode_box_autoadd_update_report_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ItemReport sse_decode_item_report(SseDeserializer deserializer);

  @protected
  ItemStatus sse_decode_item_status(SseDeserializer deserializer);

  @protected
  List<ItemReport> sse_decode_list_item_report(SseDeserializer deserializer);

  @protected
  List<MatchReason> sse_decode_list_match_reason(SseDeserializer deserializer);

  @protected
  List<MatchResult> sse_decode_list_match_result(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MatchReason sse_decode_match_reason(SseDeserializer deserializer);

  @protected
  MatchResult sse_decode_match_result(SseDeserializer deserializer);

  @protected
  NewReportInput sse_decode_new_report_input(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ItemStatus? sse_decode_opt_box_autoadd_item_status(
    SseDeserializer deserializer,
  );

  @protected
  ReportType sse_decode_report_type(SseDeserializer deserializer);

  @protected
  Statistics sse_decode_statistics(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateReportInput sse_decode_update_report_input(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_item_status(
    ItemStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_report_input(
    NewReportInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_update_report_input(
    UpdateReportInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_item_report(ItemReport self, SseSerializer serializer);

  @protected
  void sse_encode_item_status(ItemStatus self, SseSerializer serializer);

  @protected
  void sse_encode_list_item_report(
    List<ItemReport> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_match_reason(
    List<MatchReason> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_match_result(
    List<MatchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_match_reason(MatchReason self, SseSerializer serializer);

  @protected
  void sse_encode_match_result(MatchResult self, SseSerializer serializer);

  @protected
  void sse_encode_new_report_input(
    NewReportInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_item_status(
    ItemStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_report_type(ReportType self, SseSerializer serializer);

  @protected
  void sse_encode_statistics(Statistics self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_report_input(
    UpdateReportInput self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
